name: SimpleCometElevator
version: '1.21.x-1.0.0'
main: H_Amase.simpleCometElevator.SimpleCometElevator
api-version: '1.21'

commands:
  simplecometelevator:
    description: SimpleCometElevator admin command
    usage: "/<command> <reload|get|set|help>"
    aliases: [scelevator]
    permission: simplecometelevator.admin

permissions:
  simplecometelevator.admin:
    description: Allows reloading and editing SimpleCometElevator config
    default: op
